apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-proxy
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ template "fullname" . }}-proxy
      volumes:
        - name: {{ template "fullname" . }}-proxy
          configMap: { name: {{ template "fullname" . }}-proxy }
      containers:
        - name: {{ template "fullname" . }}-proxy
          volumeMounts:
          - { name: {{ template "fullname" . }}-proxy, mountPath: /etc/traefik/ }
          image: traefik:1.4.0-rc3
          resources:
            requests: { cpu: 50m, memory: "64Mi" }
            limits: { memory: "128Mi" }
          ports:
            [ { containerPort: 80 },  { containerPort: 443 }, { containerPort: 8080 }]
          livenessProbe: { httpGet: { path: /health, port: 8080 } }
          readinessProbe: { httpGet: { path: /health, port: 8080 } }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - { port: 80, targetPort: 80, name: http }
    - { port: 443, targetPort: 443, name: https }
  selector:
    app: {{ template "name" . }}-proxy
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  traefik.toml: |-
    {{ include "traefik.toml" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "endpoints", "secrets"]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ template "name" . }}-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  backend:
    serviceName: {{ template "fullname" . }}-proxy
    servicePort: 80
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" . }}-proxy
            servicePort: 80
